### ISSUE TITLE
Update Data APIs to use Version reference in the request mapping

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-aspsp#252]
## Story
As an OB sandbox PSU user
I want the Data API to support the versions implemented of the OBIE spec
so that I can import / export and test against each version

## Acceptance criteria
* v3.1.1 Data API version mapping supported.
* v3.1.2 Data API version mapping supported.
* v3.1.3 Data API version mapping supported.
* v3.1.4 Data API version mapping supported.
* v3.1.5 Data API version mapping supported.
* v3.1.6 Data API version mapping supported.

## Tasks list
- [ ] Update the Data APIs to use the version mapping
- [ ] Check the postman test to use the new context request mapping implementation version reference
- [ ] Update postman test

### Release Notes
* Affected API: Data-API
* Description: The Data API endpoints now support the above versions.
