### ISSUE TITLE
Event Notification - Callback URL api

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-aspsp#297]
## Change Description

1. A Tpp can get the callback url accessing by newer api.
`An ASPSP must allow a callback-url resource to be accessed in a newer version.`
Example: *Access to callback resource created in v3.0 from v3.1 or newer*

1. Change the response when doesn't exist callback url resources.
`A TPP must not access a callback-url on an older version, via the CallbackUrlId for a callback-url created in a newer version`

   When the tpp request the callback URL resources:
   - *When the resources has been created on a newer version the response will be empty with http code 200.*
   - *When doesn't exist tpp callback URL resources the response will be empty with http code 200.*

## Tasks
List of tasks required to implement this story:
- [x] Callback URL API checks
   - [x] Check Integration Tests and create more if necessary
   - [x] Check functional test and create more if necessary
   - [ ] Check Postman test and create more if necessary
