### ISSUE TITLE
Aggregated Polling API Scopes by version (Event Notification API)

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-aspsp#327]
## Description
To access Aggregated Polling API the access token must have a specific scopes.
The defined scopes to access Aggregated Polling API are different between versions.

**Scopes by version table**
| Scope | version | document |
| --- | --- | --- |
| eventpolling | 3.1.2 | [AggregatedPolling-v3.1.2-Scopes](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1077806765/Aggregated+Polling+-+v3.1.2#AggregatedPolling-v3.1.2-Scopes) |
| eventpolling | 3.1.3 | [AggregatedPolling-v3.1.3-Scopes](https://openbankinguk.github.io/read-write-api-site3/v3.1.3/profiles/aggregated-polling-api-profile.html#scopes) |
| accounts, fundsconfirmations | 3.1.4 | [AggregatedPolling-v3.1.4-Scopes](https://openbankinguk.github.io/read-write-api-site3/v3.1.4/profiles/aggregated-polling-api-profile.html#scopes) |
| accounts, fundsconfirmations | 3.1.5 | [AggregatedPolling-v3.1.5-Scopes](https://openbankinguk.github.io/read-write-api-site3/v3.1.5/profiles/aggregated-polling-api-profile.html#scopes) |
| accounts, fundsconfirmations | 3.1.6 | [AggregatedPolling-v3.1.6-Scopes](https://openbankinguk.github.io/read-write-api-site3/v3.1.6/profiles/aggregated-polling-api-profile.html#scopes) |
| accounts, fundsconfirmations | 3.1.7 (no implemented yet)| [AggregatedPolling-v3.1.7-Scopes](https://openbankinguk.github.io/read-write-api-site3/v3.1.7/profiles/aggregated-polling-api-profile.html#scopes) |

## Tasks
- [x] Check the authorisation scopes defined in the implemented controllers
- [x] Fix the scopes by version
- [x] Create integration tests
- [x] Check the functional tests and apply fixes if necessary
- [x] Check Postman `End To End Tests (Generated)` collection and apply fixes if necessary
