### ISSUE TITLE
Wrong Grant type for /{ConsentId}/funds-confirmation endpoints (payments API)

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-aspsp#434]
### Issues related
- [Parent Issue](https://github.com/ForgeCloud/ob-deploy/issues/766)
### Description
The payments endpoints FundsConfirmation have a wrong grant_type set 
When **TPP** request an access token with "grant_type": "authorization_code" the implementation expect an access_token with "grant_type": "client_credential" .

The documentation [api spec 3.1.6](https://openbankinguk.github.io/read-write-api-site3/v3.1.6/resources-and-data-models/pisp/domestic-payment-consents.html) define "grant_type": "authorization_code" for the below endpoints:
-  /domestic-payment-consents/{ConsentId}/funds-confirmation
- /international-payment-consents/{ConsentId}/funds-confirmation
- /international-scheduled-payment-consents/{ConsentId}/funds-confirmation

### Tasks
- [x] Check all funds-confirmation payment endpoints to identify a wrong grant_type.
- [x] Fix the grant_type for funds-confirmation payment endpoints identified with a wrong grant_type.
- [x] Improve integration test to cover the cases.
- [x] Fix / Create functional tests to cover the cases.
